remote_theme: just-the-docs/just-the-docs
title: Codex_Ius
description: Portal de Educación Jurídica Argentina
search: true

aux_links:
  LinkedIn: www.linkedin.com/in/rodrigoquiroga-codexius
  GitHub: https://github.com/codex-ius/codex-ius.github.io

collections:
  legislacion:
    output: true
    permalink: /:collection/:name/

nav_sort: case_sensitive
