remote_theme: just-the-docs/just-the-docs

title: Codex_Ius
description: Portal de Educación Jurídica Argentina

# URL correcta para tu repo
url: "https://codex-ius.github.io"
baseurl: ""  # ← VACÍO porque es usuario.github.io

# Navegación
nav:
  - Legislación: legislacion/_index.md

# Just the Docs
search: true
color_scheme: dark

aux_links:
  LinkedIn: "https://www.linkedin.com/in/rodrigoquiroga-codexius"
  GitHub: "https://github.com/codex-ius/codex-ius.github.io"

collections:
  legislacion:
    output: true
    permalink: /legislacion/:name/
  sources:
    output: true
    permalink: /sources/:name/
