remote_theme: just-the-docs/just-the-docs
title: Codex_Ius
description: Portal de Educación Jurídica Argentina
search: true

color_scheme: default

aux_links:
  LinkedIn: https://linkedin.com/in/rodrigo-quiroga
  GitHub: https://github.com/RodrigoAQuiroga
