remote_theme: just-the-docs/just-the-docs
title: Codex_Ius
description: Portal de Educación Jurídica Argentina

# ORDEN FIJO (Home primero)
nav:
  - Home: index.md
  - Legislación: legislacion/_index.md

search: true
aux_links:
  LinkedIn: https://www.linkedin.com/in/rodrigoquiroga-codexius
  GitHub: https://github.com/codex-ius/codex-ius.github.io

collections:
  legislacion:
    output: true
    permalink: /legislacion/:name/
